on:
  push:
    branches:
      - main

name: "Testing"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run Tests"
        run: go test
      - name: "Build Executable"
        run: go build main.go
      - name: "Run Benchmark"
        run: time ./main
